TRUNCATE TABLE categories;

ALTER SEQUENCE id RESTART WITH 1;

INSERT INTO categories (name, project_id) VALUES ('JavaScript', 1);
INSERT INTO categories (name, project_id) VALUES ('JQuery', 1);
INSERT INTO categories (name, project_id) VALUES ('React', 1);
INSERT INTO categories (name, project_id) VALUES ('Python', 1);
INSERT INTO categories (name, project_id) VALUES ('JavaScript', 2);
INSERT INTO categories (name, project_id) VALUES ('React', 2);
INSERT INTO categories (name, project_id) VALUES ('php', 2);
INSERT INTO categories (name, project_id) VALUES ('Angular', 2);
INSERT INTO categories (name, project_id) VALUES ('Ruby', 2);
INSERT INTO categories (name, project_id) VALUES ('JavaScript', 3);
INSERT INTO categories (name, project_id) VALUES ('React', 3);
INSERT INTO categories (name, project_id) VALUES ('php', 3);
INSERT INTO categories (name, project_id) VALUES ('JavaScript', 4);
INSERT INTO categories (name, project_id) VALUES ('JQuery', 4);
INSERT INTO categories (name, project_id) VALUES ('React', 4);
INSERT INTO categories (name, project_id) VALUES ('Ruby', 4);
INSERT INTO categories (name, project_id) VALUES ('Postgres', 4);
INSERT INTO categories (name, project_id) VALUES ('Elixir', 4);
INSERT INTO categories (name, project_id) VALUES ('Python', 4);
INSERT INTO categories (name, project_id) VALUES ('JavaScript', 5);
INSERT INTO categories (name, project_id) VALUES ('Angular', 5);
INSERT INTO categories (name, project_id) VALUES ('Ruby', 5);
INSERT INTO categories (name, project_id) VALUES ('JavaScript', 6);
INSERT INTO categories (name, project_id) VALUES ('JQuery', 6);
INSERT INTO categories (name, project_id) VALUES ('React', 6);
INSERT INTO categories (name, project_id) VALUES ('JavaScript', 7);
INSERT INTO categories (name, project_id) VALUES ('React', 7);
INSERT INTO categories (name, project_id) VALUES ('Ruby', 7);
INSERT INTO categories (name, project_id) VALUES ('JavaScript', 8);
INSERT INTO categories (name, project_id) VALUES ('React', 8);
INSERT INTO categories (name, project_id) VALUES ('JavaScript', 9);
INSERT INTO categories (name, project_id) VALUES ('JQuery', 9);
INSERT INTO categories (name, project_id) VALUES ('React', 9);
INSERT INTO categories (name, project_id) VALUES ('JavaScript', 10);
INSERT INTO categories (name, project_id) VALUES ('React', 10);
INSERT INTO categories (name, project_id) VALUES ('Angular', 10);
INSERT INTO categories (name, project_id) VALUES ('Ruby', 10);
INSERT INTO categories (name, project_id) VALUES ('Rails', 10);
